"user-client"
import HomeContainer from "@/component/Home/HomeContainer";
import { Poppins } from "@next/font/google";
import Head from "next/head";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({ weight: ["700", "400"], preload: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>HEART TO SERVE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* google font */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Anton&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>
      <main className={`${poppins.className} overflow-x-hidden`}>
        <Toaster />
        <HomeContainer />
      </main>
      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      <script>
        AOS.init();
      </script>
    </>
  );
}
