import AntiDrugCampaign from "@/component/AntiDrugCampaign";
import Form from "@/component/Form";
import { Poppins } from "@next/font/google";
import Head from "next/head";

// const Poppins = Poppins({ weight: 700 });


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Form></Form>
        <AntiDrugCampaign></AntiDrugCampaign>
      </main>
    </>
  );
}
